"""Add subcategories and update incident schema

Revision ID: 2b97a18b7e95
Revises: 3fb257e21686
Create Date: 2026-02-12 17:16:43.114827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b97a18b7e95'
down_revision: Union[str, Sequence[str], None] = '3fb257e21686'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subcategories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(op.f('categories_department_id_fkey'), 'categories', type_='foreignkey')
    op.drop_column('categories', 'department_id')
    op.add_column('incidents', sa.Column('subcategory_id', sa.UUID(), nullable=True))
    op.alter_column('incidents', 'department_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_foreign_key(None, 'incidents', 'subcategories', ['subcategory_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'incidents', type_='foreignkey')
    op.alter_column('incidents', 'department_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('incidents', 'subcategory_id')
    op.add_column('categories', sa.Column('department_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('categories_department_id_fkey'), 'categories', 'departments', ['department_id'], ['id'])
    op.drop_table('subcategories')
    # ### end Alembic commands ###
