"""add_function_failure_and_mode

Revision ID: 3afae3f56550
Revises: 7a426f621558
Create Date: 2026-02-13 15:28:23.475139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3afae3f56550'
down_revision: Union[str, Sequence[str], None] = '7a426f621558'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problems', sa.Column('function_failure', sa.Text(), nullable=True))
    op.add_column('problems', sa.Column('failure_mode', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('problems', 'failure_mode')
    op.drop_column('problems', 'function_failure')
    # ### end Alembic commands ###
