"""add_problem_change_sla_catalog

Revision ID: 8835b3dedc69
Revises: 25e46a951e0f
Create Date: 2026-02-13 12:31:39.418517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '8835b3dedc69'
down_revision: Union[str, Sequence[str], None] = '25e46a951e0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problems',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sla_policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('priority', postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='incidentpriority', create_type=False), nullable=False),
    sa.Column('response_time_minutes', sa.Integer(), nullable=True),
    sa.Column('resolution_time_minutes', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('priority')
    )
    op.create_table('service_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('base_priority', postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='incidentpriority', create_type=False), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('change_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('risk_level', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('problem_id', sa.UUID(), nullable=True),
    sa.Column('requester_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('scheduled_start', sa.DateTime(), nullable=True),
    sa.Column('scheduled_end', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('incidents', sa.Column('problem_id', sa.UUID(), nullable=True))
    op.add_column('incidents', sa.Column('service_item_id', sa.UUID(), nullable=True))
    op.add_column('incidents', sa.Column('sla_breach_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'incidents', 'service_items', ['service_item_id'], ['id'])
    op.create_foreign_key(None, 'incidents', 'problems', ['problem_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'incidents', type_='foreignkey')
    op.drop_constraint(None, 'incidents', type_='foreignkey')
    op.drop_column('incidents', 'sla_breach_at')
    op.drop_column('incidents', 'service_item_id')
    op.drop_column('incidents', 'problem_id')
    op.drop_table('change_requests')
    op.drop_table('service_items')
    op.drop_table('sla_policies')
    op.drop_table('problems')
    # ### end Alembic commands ###
