"""add_rcfa_and_5whys_to_problem

Revision ID: c329d1726cbe
Revises: 8835b3dedc69
Create Date: 2026-02-13 14:18:54.221737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c329d1726cbe'
down_revision: Union[str, Sequence[str], None] = '8835b3dedc69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problems', sa.Column('rcfa_analysis', sa.Text(), nullable=True))
    op.add_column('problems', sa.Column('five_whys', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('problems', 'five_whys')
    op.drop_column('problems', 'rcfa_analysis')
    # ### end Alembic commands ###
