"""update_problem_status_and_add_creator

Revision ID: e881439f19e2
Revises: 3afae3f56550
Create Date: 2026-02-13 16:57:06.332949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e881439f19e2'
down_revision: Union[str, Sequence[str], None] = '3afae3f56550'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problems', sa.Column('creator_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'problems', 'users', ['creator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'problems', type_='foreignkey')
    op.drop_column('problems', 'creator_id')
    # ### end Alembic commands ###
